### ISSUE TITLE
Apply binary fixups using patchelf

### ISSUE THREAD

**Issue by mboes** [tweag/clodl#1]
Currently we require that the user do two things manually:

1. make sure the binary to jarify depends on `libHSjarify*.so`,
2. link as a PIE, turn on origin processing and add `$ORIGIN` to the `RPATH`.

Linking as PIE will always be the responsibility of the user. But the rest we can do ourselves, using `patchelf`. An alternative is [elf-edit](https://github.com/GaloisInc/elf-edit), but the editing facilities for that lib are not powerful enough yet (can't figure out how to edit dynamic section).

We now have the `patchelf` codebase imported as vendor code. We even build it from `Setup.hs`. But we don't use it. Let's use it to:

1. Inject a dependency on the cbits/bootstrap.c code.
2. Inject `$ORIGIN` into the `RPATH` using `--set-rpath`.

**Comment by facundominguez** [comment]
Is this issue still relevant? clodl should probably be concerned with making the zipped closure only.
